---
title: "chickwts"
author: "Mansour"
date: "10/17/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE, 
                      message = FALSE,
                      warning = FALSE,
                      echo = FALSE,
                      autodep = TRUE, 
                      fig.align = "center")

library(tidyverse)
library(rio)
library(scales)
library(GGally)
library(ggplot2)

```

```{r}

library(tidyverse)
library(knitr)
```

*Compare different food effects on the growth rate of chickens*

```{r output="asis"  ,echo = FALSE}

chickwts %>% 
  group_by(feed) %>%
 summarise(n = n(),
               average = mean(weight),
               SD = sd(weight))
  
```
**below plots gives more insights about food effects on chicken weights** 



**PLOTS**

```{r, echo=FALSE}
ggplot(chickwts, aes( x = feed, y =  weight )) + 
  geom_boxplot()
```



```{r, echo = FALSE}
ggplot(chickwts,aes(x=feed, y=weight)) + 
  geom_jitter() + 
  stat_summary(fun.data = mean_sdl,
               fun.args = list(mult=1),
               color="red")
```

measure the impact of food on chicken weight 





```{r}
chickwts_lm <- lm(weight ~ feed , data =  chickwts)
chickwts_lm
anova(chickwts_lm)

```
  
```



```{r}
lm(formula = weight ~ feed, data = chickwts)

```

